#:schema node_modules/wrangler/config-schema.json
name = "launchtube"
main = "dist/index.js"
compatibility_date = "2024-05-12"
workers_dev = true
minify = true

[[durable_objects.bindings]]
name = "CREDITS_DURABLE_OBJECT"
class_name = "CreditsDurableObject"

[[durable_objects.bindings]]
name = "SEQUENCER_DURABLE_OBJECT"
class_name = "SequencerDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["FeeBumpDurableObject"]

[[migrations]]
tag = "v2"
new_classes = ["SequencerDurableObject"]

[[migrations]]
tag = "v3"
renamed_classes = [{from = "FeeBumpDurableObject", to = "CreditsDurableObject" }]

[[kv_namespaces]]
binding = "SUDOS"
id = "1fcab4e76e4948ba9b728271fa51586d"

[[d1_databases]]
binding = "DB"
database_name = "launchtube-testnet"
database_id = "80e789b8-41a6-4741-aeca-62b4203661dc"

[build]
command = "npm run build"

[define]
global = "globalThis"

[vars]
ENV = "development"