#:schema node_modules/wrangler/config-schema.json
name = "feebump"
main = "dist/index.js"
compatibility_date = "2024-05-12"
workers_dev = true
minify = true

[[durable_objects.bindings]]
name = "FEEBUMP_DURABLE_OBJECT"
class_name = "FeeBumpDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["FeeBumpDurableObject"]

[[kv_namespaces]]
binding = "SUDOS"
id = "1fcab4e76e4948ba9b728271fa51586d"

[build]
command = "npm run build"

[define]
global = "globalThis"